### ISSUE TITLE
[FEAT]: Single Products API 

### ISSUE THREAD

**Issue by urizennnn** [hngprojects/hng_boilerplate_golang_web#120]
# API Endpoint: Retrieve Single Product Information

## Description

Develop API endpoint that retrieves information about a single product. The response includes product details such as ID, name, description, price, and availability.

## Acceptance Criteria

- The endpoint `/api/v1/products/{product-id}` is accessible via a GET request.
- When a valid product-id is provided, the endpoint returns a 200 OK status.
- When an invalid product-id format is provided, the endpoint returns a 400 Bad Request status.
- On an invalid request, the response body contains an error message indicating the invalid product ID format.
- When a product-id that does not exist is provided, the endpoint returns a 404 Not Found status.
- For a product that does not exist, the response body contains an error message indicating that the product was not found.
- If an unexpected server error occurs, the endpoint returns a 500 Internal Server Error status.
- The response body of an error 500 response contains an error message indicating that an unexpected error occurred.
- Ensure that all unit and integration tests for the fetch single product endpoint are comprehensive, and verify the functionality correctly.

## Purpose

This provides a backend service that allows fetching detailed information on selected/specific product.

## Requirements

1. Implement an endpoint to view single product
2. Return detailed information on products
3. Handle situations where products don't exist

## Expected Outcome

API endpoint that returns detailed information on specific product

## Tasks

1. Create an endpoint `/api/v1/products/{product-id}` to fetch details of a single product.
2. Implement server-side logic to handle successful and failed product retrieval requests.
3. Ensure all sensitive data is encrypted and secure.
4. Implement logging for errors and product retrieval attempts.
5. Write unit tests for the fetch single product endpoint.
6. Write integration tests for the fetch single product logic.
7. Perform security testing to ensure data protection and compliance.

## Database Schema

```sql
Table products {
  id int [pk, increment]
  name varchar(255) [not null]
  description text
  price decimal(10,2) [not null]
  available boolean [default: true]
  category varchar(255)
  created_at timestamp [default: `current_timestamp`]
  updated_at timestamp [default: `current_timestamp`]
}
```

## Endpoint

URL: `GET /api/v1/products/{product-id}`

### Success Response
Code: 200 OK
Content:
```json
{
  "product": {
    "id": "string",
    "name": "string",
    "description": "string",
    "price": "number",
    "available": "boolean",
    "category": "string",
    "created_at": "string",
    "updated_at": "string"
  }
}
```

#### Code: 400 BAD REQUEST
Content:
```json
{
  "error": "Invalid product ID"
}
```

#### Code: 404 NOT FOUND
Content:
```json
{
  "error": "Product not found"
}
```

#### Code 422: UNPROCESSABLE CONTENT / VALIDATION ERROR
Content:
```json
{
  "errors": {
    "field": "",
    "message": ""
  }
}
```

#### Code: 500 INTERNAL SERVER ERROR
Content:
```json
{
  "error": "An unexpected error occurred"
}
```

**Comment by michaelcosj** [comment]
@urizennnn I can work on this
